name: Welcome comment

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congrats, you spotted an issue. To be honest, this is a side project for homework, so don't expect regular maintenance."
          pr-message: "Thank you for your pull request. We will diligently look review it for effectiveness. Ugh, seriously? Why do we even get pull requests? Come on! Oh, wait, did I turn of the transcriber? There...CLICK"